version: '2'

services:
  pg:
    image: 'postgres:alpine'
    container_name: 'pg'
    environment:
      - POSTGRES_USER=dn
      - POSTGRES_PASSWORD=secret
      - PGDATA=/pgdata
      - POSTGRES_DB=dn
    volumes:
      - 'pgdata:/pgdata'
    networks:
      - db
  dummynews:
    image: 'videah/dn'
    build: .
    container_name: 'dn'
    networks:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://dn:secret@pg/dn
    ports:
      - '80:80'

networks:
  db:
    external: true
volumes:
  pgdata: